FROM fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch7

ADD fluentd.conf /fluentd/etc/fluent.conf
ADD fluentd-k8s.conf /fluentd/etc/fluentd-k8s.conf
ADD fluentd-nginx.conf /fluentd/etc/fluentd-nginx.conf
