name: BUILD S3CMD
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

env:
  TAG_S3CMD: latest

jobs:              
  running:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build image and add tags
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/s3cmd:$TAG_S3CMD ./s3cmd/
        
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/s3cmd:$TAG_S3CMD
