name: BUILD & TEST to GCR
on:
  workflow_dispatch:
    paths: 
      - 'test/*'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
env:
  IMAGE_NAME: nginx
  TAG: 1.0.${{ github.run_number }}
jobs:
  build:
    name: Build and push nginx latest image

    runs-on: ubuntu-latest
    # if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ secrets.USERNAME }} --password-stdin
        
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
        
      - name: Build Nginx image
        run: |
          cd test
          docker build --tag ghcr.io/duyhenryer/$IMAGE_NAME:$TAG .

      - name: Push image to GitHub Container Registry
        run: |
          docker push ghcr.io/duyhenryer/$IMAGE_NAME:$TAG
