name: Build Docker
on: 
  workflow_dispatch:
#     inputs:
#       logLevel:
#         description: 'Feature purpose only'     
#         required: true
#         default: 'warning'
  push:
    branches:    
#       - '*'         # matches every branch that doesn't contain a '/'
      - main     # matches every branch containing a single '/'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build image and add tags
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-v2 .
        
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/docker-v2
