name: Build fluentd
on:
  workflow_dispatch:
env:
  IMAGE_TAG: v1
  FLUENTD_REPO: fluentd

jobs:
  build_push_ecr:
    name: Build and push fluentd to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build image and add tags
        run: |
          cd fluentd
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$FLUENTD_REPO:$IMAGE_TAG .
        
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/$FLUENTD_REPO:$IMAGE_TAG
