name: BUILD & TEST to GCR
on:
  workflow_dispatch:
    paths: 
      - 'test/*'
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - 'test/*'

env:
  IMAGE_NAME: nginx
  TAG: 1.0.${{ github.run_number }}
jobs:
  build:
    name: Build and push nginx latest image

    runs-on: ubuntu-latest
    # if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ secrets.USERNAME }} --password-stdin
        
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
        
      - name: Build Nginx image
        run: |
          cd test
          docker build --tag ghcr.io/duyhenryer/$IMAGE_NAME:$TAG .

      - name: Push image to GitHub Container Registry
        run: |
          docker push ghcr.io/duyhenryer/$IMAGE_NAME:$TAG
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: git_action_bot
      uses: bryannice/gitactions-slack-notification@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: 'Slack Notification'
        SLACK_MESSAGE: 'Message to the Slack Notification'
        SLACK_ICON: 'https://github.com/duyhenryer.png?size=48'
        SLACK_COLOR: '#efefef'
        SLACK_USERNAME: 'git_action_bot'
        GITHUB_ACTOR: ${GITHUB_ACTOR}
        GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
        GITHUB_REF: ${GITHUB_REF}
        GITHUB_ACTION: ${GITHUB_ACTION}
        GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}
 
