name: BUILD PYTHON
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

# env:
  #  tags image's name.
#   TAG_IMAGE_7.2: 7.2
#   TAG_IMAGE_7.3: 7.3
#   TAG_IMAGE_7.4: 7.4
#   TAG_IMAGE_LATEST: latest

jobs:              
  running:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    strategy:
      matrix:
        version: ["3.8"]
    steps:
      - uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build image and add tags
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/python:${{ matrix.version }} ./python/${{ matrix.version }}
        
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/python:${{ matrix.version }}
