name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  #  tags image's name.
  TAG_IMAGE_7.2: 7.2
  TAG_IMAGE_7.3: 7.3
  TAG_IMAGE_7.4: 7.4
  TAG_IMAGE_LATEST: latest

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["latest", "7.4", "7.3", "7.2"]
    steps:
      - uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        
      # - name: Build image
       # run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Build and Push image to DockerHub
        run: |
          # IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

          # Use Docker `latest` tag convention
          # [ "$VERSION" == "main" ] && VERSION=latest

          # echo IMAGE_ID=$IMAGE_ID
          # echo VERSION=$VERSION
          
          docker build . --file /php/fpm/${{ matrix.version }}/Dockerfile
          docker tag $DOCKERHUB_USERNAME/${{ matrix.version }}
          docker push $DOCKERHUB_USERNAME/${{ matrix.version }}
