name: CI TEST
on:
  workflow_dispatch:

env:
  CORE_ACCESS_TOKEN: ${{ secrets.CORE_ACCESS_TOKEN }}
#   export GITHUB_PAT=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

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    - name: Generate build ID
      id: prep
      run: |
          git config --global user.email "daonv@fireapps.vn"
          git config --global user.name "daonvfireapps"
          git config --global credential.helper store

          echo https://duyhenryer:$CORE_ACCESS_TOKEN@github.com > ~/.git-credentials

          ls -al
          git clone https://github.com/YoungWorldTechnology/lb-core.git
          ls -al
          ls -al lb-core
          
          docker build -t xxxxx . --build-arg CORE_ACCESS_TOKEN=$CORE_ACCESS_TOKEN
        
