name: CI TEST
on:
  workflow_dispatch:

env:
  CORE_ACCESS_TOKEN: ${{ secrets.CORE_ACCESS_TOKEN }}
#   export GITHUB_PAT=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

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    - name: Generate build ID
      id: prep
      run: |

          
          docker build --build-arg CORE_ACCESS_TOKEN=$CORE_ACCESS_TOKEN -t xxxx:zzzz .

