name: CI TEST
on:
  workflow_dispatch:

env:
  CORE_ACCESS_TOKEN: ${{ secrets.CORE_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    - name: Generate build ID
      id: prep
      run: |
          git config --global user.email "duyhenry250897@gmail.com"
          git config --global user.name "duyhenryer"
          git config --global user.password "$CORE_ACCESS_TOKEN"
          git config --global credential.helper store

          ls -al
          git clone https://github.com/YoungWorldTechnology/lb-core.git
          ls -al
          ls -al lb-core
        
