name: Test env
on: 
  workflow_dispatch:
#     inputs:
#       logLevel:
#         description: 'Feature purpose only'     
#         required: true
#         default: 'warning'
  push:
    branches:    
#       - '*'         # matches every branch that doesn't contain a '/'
      - feature/MS-9999       # matches every branch containing a single '/'
#       - '**'        # matches every branch
      - '!main'   # excludes master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Generate build ID
        id: prep
        run: |
            branch=${GITHUB_REF#refs/heads/}
            sha=${GITHUB_SHA::8}
            ts=$(date +%s)
            echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"  

            echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
            echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
            echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: echo
        run: |
          echo ${{ steps.prep.outputs.BUILD_ID }}
          echo ${GITHUB_REF##*/}
          
          echo ${{ steps.branch_name.outputs.SOURCE_NAME }}
          echo ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
          echo ${{ steps.branch_name.outputs.SOURCE_TAG }}
          
          
          
