# This is a basic workflow to help you get started with Actions

name: CI TEST

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-push:
    env:
        IMAGE: duyhenryer
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Generate build ID
      id: prep
      run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"

#     - name: Build and publish container image with tag
#       uses: docker/build-push-action@v2
#       with:
#           push: true
#           context: .
#           file: ./Dockerfile
#           tags: |
#             ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}

    - name: setup env
      env:
        DB_PASSWORD: ${{ secrets.STAG_DB_PASSWORD }}
        DB_SLAVE_PASSWORD: ${{ secrets.STAG_DB_SLAVE_PASSWORD }}
        DB_CORE_PASSWORD: ${{ secrets.STAG_DB_CORE_PASSWORD }}
        DB_MONGO_PASSWORD: ${{ secrets.STAG_DB_MONGO_PASSWORD }}
        MAILGUN_SECRET: ${{ secrets.STAG_MAILGUN_SECRET }}

        # and more
      run: |
        envsubst < .env > .env
        cat .env
          
    - name: Push image to GitHub Container Registry
      run: |
        echo ${{ steps.prep.outputs.BUILD_ID }}     
        eche ${{  }}
          
          
        
