name: Test env
on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            -   uses: actions/checkout@v1

            -   name: Setup SSH Keys and known_hosts
                run: |
                    ssh-keygen
                    ls -al ~/.ssh
                    # ssh-add <<< "${{ secrets.SSH_PRIVATE_KEY }}"

            -   name: Some task that fetches dependencies
                run: echo "${{ secrets.SSH_PRIVATE_KEY }}"