name: CI TEST
on:
  workflow_dispatch:
  push:
    branches:
    - main
env:
  GIT_ACCESS_TOKEN_LB_CORE: ${{ secrets.GIT_ACCESS_TOKEN_LB_CORE }}
#   export GITHUB_PAT=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

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    - name: Generate build ID
      id: prep
      run: |

          
          docker build --build-arg GIT_ACCESS_TOKEN_LB_CORE=$GIT_ACCESS_TOKEN_LB_CORE -t xxxx:zzzz .

