name: CI TEST
on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Generate build ID
      id: prep
      run: |
          ls -al
          https://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@github.com/YoungWorldTechnology/lb-core.git
          ls -al
        
