name: Test env
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Feature purpose only'     
        required: true
        default: 'warning'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Generate build ID
        id: prep
        run: |
            branch=${GITHUB_REF##*/}
            sha=${GITHUB_SHA::8}
            ts=$(date +%s)
            echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"  
            
      - name: echo
        run: |
          echo ${{ steps.prep.outputs.BUILD_ID }}
